services:
  - type: worker
    name: lootbox-role-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
